# Estado Civil
dic_estado_civil = {
    1: "Soltero",
    2: "Casado",
    3: "Viudo",
    4: "Divorciado",
    5: "Unión de hecho",
    6: "Separado legalmente"
}

# Nacionalidad
dic_nacionalidad = {
    1: "Portugués",
    2: "Alemán",
    3: "Español",
    4: "Italiano",
    5: "Holandés",
    6: "Inglés",
    7: "Lituano",
    8: "Angoleño",
    9: "Cabo Verdeano",
    10: "Guineano",
    11: "Mozambiqueño",
    12: "Santomense",
    13: "Turco",
    14: "Brasileño",
    15: "Rumano",
    16: "Moldavo (República de)",
    17: "Mexicano",
    18: "Ucraniano",
    19: "Ruso",
    20: "Cubano",
    21: "Colombiano"
}

# Curso
dic_curso = {
    1: "Tecnologías de Producción de Biocombustibles",
    2: "Animación y Diseño Multimedia",
    3: "Servicio Social (asistencia nocturna)",
    4: "Agronomía",
    5: "Diseño de Comunicación",
    6: "Enfermería Veterinaria",
    7: "Ingeniería Informática",
    8: "Equinotecnia",
    9: "Gestión",
    10: "Servicio Social",
    11: "Turismo",
    12: "Enfermería",
    13: "Higiene Oral",
    14: "Gestión Publicitaria y de Marketing",
    15: "Periodismo y Comunicación",
    16: "Educación Básica",
    17: "Gestión (asistencia nocturna)"
}

# Calificación Previa
dic_calificacion_previa = {
    1: "Educación Secundaria",
    2: "Educación Superior—Grado universitario",
    3: "Educación Superior—Licenciatura",
    4: "Educación Superior—Máster",
    5: "Educación Superior—Doctorado",
    6: "Frecuencia de educación superior",
    7: "12° año escolar—no completado",
    8: "11° año escolar—no completado",
    9: "Otro—11° año escolar",
    10: "10° año escolar",
    11: "10° año escolar—no completado",
    12: "Educación Básica ciclo 3 (9°/10°/11° año) o equivalente",
    13: "Educación Básica ciclo 2 (6°/7°/8° año) o equivalente",
    14: "Curso de especialización tecnológica",
    15: "Educación superior—Licenciatura (primer ciclo)",
    16: "Curso técnico superior profesional",
    17: "Educación superior—Máster (segundo ciclo)"
}

# Calificación de la Madre y el Padre
dic_calificacion_madre_padre = {
    1: "Educación Secundaria—12° Año Escolar o Equivalente",
    2: "Educación Superior—Grado universitario",
    3: "Educación Superior—Licenciatura",
    4: "Educación Superior—Máster",
    5: "Educación Superior—Doctorado",
    6: "Frecuencia de Educación Superior",
    7: "12° Año Escolar—no completado",
    8: "11° Año Escolar—no completado",
    9: "7° Año (Antiguo)",
    10: "Otro—11° Año Escolar",
    11: "Curso complementario de secundaria de 2° año",
    12: "10° Año Escolar",
    13: "Curso general de comercio",
    14: "Educación Básica ciclo 3 (9°/10°/11° Año) o Equivalente",
    15: "Curso Complementario de Secundaria",
    16: "Curso técnico-profesional",
    17: "Curso Complementario de Secundaria—no concluido",
    18: "7° año de escolaridad",
    19: "Ciclo 2 del curso general de secundaria",
    20: "9° Año Escolar—no completado",
    21: "8° año de escolaridad",
    22: "Curso General de Administración y Comercio",
    23: "Contabilidad y Administración Suplementaria",
    24: "Desconocido",
    25: "No sabe leer ni escribir",
    26: "Sabe leer sin tener 4° de escolaridad",
    27: "Educación básica ciclo 1 (4°/5° año) o equivalente",
    28: "Educación Básica Ciclo 2 (6°/7°/8° Año) o equivalente",
    29: "Curso de especialización tecnológica",
    30: "Educación superior—Licenciatura (primer ciclo)",
    31: "Curso de estudios superiores especializados",
    32: "Curso técnico superior profesional",
    33: "Educación Superior—Máster (segundo ciclo)",
    34: "Educación Superior—Doctorado (tercer ciclo)"
}

# Ocupación de la Madre y el Padre
dic_ocupacion_madre_padre = {
    1: "Estudiante",
    2: "Representantes del Poder Legislativo y los Organismos Ejecutivos, Directores y Gerentes Ejecutivos",
    3: "Especialistas en Actividades Intelectuales y Científicas",
    4: "Técnicos de Nivel Intermedio y Profesiones",
    5: "Personal Administrativo",
    6: "Trabajadores de Servicios Personales, Seguridad y Protección, y Vendedores",
    7: "Agricultores y Trabajadores Calificados en Agricultura, Pesca y Silvicultura",
    8: "Trabajadores Calificados en la Industria, Construcción y Artesanía",
    9: "Operadores de Instalación y Máquinas y Trabajadores de Montaje",
    10: "Trabajadores No Calificados",
    11: "Profesiones de las Fuerzas Armadas",
    12: "Otra Situación",
    13: "Oficiales de las Fuerzas Armadas",
    14: "Sargentos de las Fuerzas Armadas",
    15: "Otro personal de las Fuerzas Armadas",
    16: "Directores de Servicios Administrativos y Comerciales",
    17: "Directores de Hotelería, Restauración, Comercio y Otros Servicios",
    18: "Especialistas en Ciencias Físicas, Matemáticas, Ingeniería y Técnicas Relacionadas",
    19: "Profesionales de la Salud",
    20: "Docentes",
    21: "Especialistas en Finanzas, Contabilidad, Organización Administrativa y Relaciones Públicas y Comerciales",
    22: "Técnicos de nivel intermedio en ciencias e ingeniería y profesiones",
    23: "Técnicos y Profesionales de Nivel Intermedio en Salud",
    24: "Técnicos de nivel intermedio en servicios legales, sociales, deportivos, culturales y similares",
    25: "Técnicos en tecnologías de la información y la comunicación",
    26: "Trabajadores de oficina, secretarios en general y operadores de procesamiento de datos",
    27: "Operadores de datos, contabilidad, servicios estadísticos, financieros y registros",
    28: "Otro personal de apoyo administrativo",
    29: "Trabajadores de servicio personal",
    30: "Vendedores",
    31: "Trabajadores de cuidado personal y similares",
    32: "Personal de servicios de protección y seguridad",
    33: "Agricultores orientados al mercado y trabajadores calificados en producción agrícola y animal",
    34: "Agricultores, ganaderos, pescadores, cazadores y recolectores, y subsistencia",
    35: "Trabajadores calificados en construcción y similares, excepto electricistas",
    36: "Trabajadores calificados en metalurgia, trabajo de metales y similares",
    37: "Trabajadores calificados en electricidad y electrónica",
    38: "Trabajadores en procesamiento de alimentos, carpintería, confección y otras industrias y artesanías",
    39: "Operadores de plantas fijas y máquinas",
    40: "Trabajadores de ensamblaje",
    41: "Conductores de vehículos y operadores de equipos móviles",
    42: "Trabajadores no calificados en agricultura, producción animal, pesca y silvicultura",
    43: "Trabajadores no calificados en la industria extractiva, construcción, manufactura y transporte",
    44: "Asistentes de preparación de alimentos",
    45: "Vendedores ambulantes (excepto alimentos) y proveedores de servicios callejeros"
}

dic_modo_postulacion = {
    1: "1ª fase—contingente general",
    2: "Ordenanza No. 612/93",
    3: "1ª fase—contingente especial (Isla de Azores)",
    4: "Titulares de otros cursos superiores",
    5: "Ordenanza No. 854-B/99",
    6: "Estudiante internacional (licenciatura)",
    7: "1ª fase—contingente especial (Isla de Madeira)",
    8: "2ª fase—contingente general",
    9: "3ª fase—contingente general",
    10: "Ordenanza No. 533-A/99, ítem b2) (Plan diferente)",
    11: "Ordenanza No. 533-A/99, ítem b3 (Otra institución)",
    12: "Mayores de 23 años",
    13: "Transferencia",
    14: "Cambio de curso",
    15: "Titulares de diploma de especialización tecnológica",
    16: "Cambio de institución/curso",
    17: "Titulares de diploma de ciclo corto",
    18: "Cambio de institución/curso (Internacional)"
}
